docs/source/acknowledgements.rst

so I wondered if we should stick to old terminal length or default to wider? ;)

DOC: example of a modeline for consistent formatting of rst using vim/emacs

---

docs/source/index.rst
docs/source/sandbox/packages.rst

I'm not done (so don't accept this yet). However, I wanted to use this pull request to spark discussion and allow you to see the progress as I go along...

Rewriting high-level architecture discussion centered on the concept of packages

---

.travis.yml
niceman/interface/tests/test_retrace.py
niceman/retrace/packagemanagers.py
niceman/retrace/tests/test_packagemanagers.py
niceman/retrace/tests/test_rpzutil.py
setup.py
tox.ini

Continued development of dpkg identification and analysis, and recording environment information into a YAML file.

ENH: Retrace Capability and Configuration File Development (WIP)

---

niceman/distribution/base.py
niceman/distribution/conda.py
niceman/distribution/debian.py
niceman/distribution/neurodebian.py
niceman/distribution/pypi.py
niceman/resource/aws_subscription.py
niceman/resource/base.py
niceman/resource/docker_container.py
niceman/resource/docker_engine.py
niceman/resource/docker_image.py
niceman/resource/ec2_image.py
niceman/resource/ec2_instance.py
niceman/resource/interface/backend.py
niceman/resource/interface/environment.py
niceman/resource/interface/image.py
niceman/resource/shell.py
niceman/resource/singularity_engine.py
niceman/resource/ssh_server.py

Got rid of the self._lgr calls.

RF: Refactored self._lgr calls out to local lgr instances.

---

niceman/cmdline/main.py

stroke me when I was looking at output of `create --clone` ;)
better ideas for a "slogan"?

DOC: fix epilog from datalad ramification

---

docs/source/cmdline.rst
niceman/interface/__init__.py
niceman/interface/start.py
niceman/interface/stop.py
niceman/resource/aws_ec2.py
niceman/resource/docker_container.py
niceman/resource/shell.py
niceman/resource/tests/test_aws_ec2.py
niceman/resource/tests/test_docker_container.py

Added start and stop commands to the niceman interface to compliment the create/delete commands.
Usage:
niceman start -r my-resource
niceman stop -r my-resource

ENH: Added start/stop interface commands.

---

.travis.yml
niceman/retrace/packagemanagers.py
niceman/retrace/tests/test_packagemanagers.py
setup.py

Address issue #77 by adding codename to origin
Note: This also updates the travis configuration to install python-apt 0.9.3.5, which works with Python 2 and 3.
TODOs

NF: Address issue #77 by adding codename to origin

---

.travis.yml
niceman/retrace/packagemanagers.py
niceman/retrace/tests/test_packagemanagers.py
setup.py
tools/ci/build_install_apt

Clearly the purpose of this branch changed. After figuring out what was different between our environments and travis' docker images, I finally got python-apt working (and a quick fix to support attrs 17.1.0)

BF: Python-apt working under Travis & support for attrs 17.1.0

---

niceman/interface/create.py
niceman/interface/tests/test_create.py

managed to miss this omission while doing the code review ;) so decided to just fix it

BF+TST: imports and test for backend_help exception handling

---

CONTRIBUTING.md

Fixes #106.
@yarikoptic would you rather this sort of silly thing just gets pushed directly back to your fork (or the main repo)?

DOC: fixed dependencies

---

.travis.yml
tools/ci/build_install_apt

BF: adjust apt installation for trusty

---

CONTRIBUTING.md

Updated CONTRIBUTING.md.  The Coverage section also lost some content with the move from nose.

DOC: updated to reflect new testing (not nose)

---

niceman/distributions/conda.py
niceman/distributions/tests/test_conda.py

Status:
- Can identify conda environments and root paths
- Associates files with packages (conda and pip)
- Conducts a test against a conda environment installed in an AppDir

ENH:  Conda Package Detection

---

niceman/distributions/conda.py
niceman/distributions/tests/test_conda.py
niceman/support/distributions/tests/test_debian.py
niceman/tests/test_tests_utils.py
niceman/tests/utils.py

This pull request addresses the code review comments and suggestions from pull request #99 .

ENH: Resolving code review suggestions for conda tracing

---

niceman/interface/retrace.py
niceman/interface/tests/test_retrace.py

BF: Open retrace output file for writing

---

.travis.yml
niceman/distributions/debian.py
niceman/distributions/tests/test_debian.py
niceman/tests/test_utils.py
niceman/utils.py

A (hopefully) more pythonic implementation of shell command batching using a generator "execute_command_batch()".  I admit that it makes the implementation easier to follow...

ENH: New generator execute_command_batch() to batch arguments of shell commands

---

niceman/resource/ssh.py
niceman/resource/tests/test_aws_ec2.py
niceman/resource/tests/test_docker_container.py
niceman/resource/tests/test_session.py
niceman/resource/tests/test_shell.py
niceman/resource/tests/test_ssh.py
niceman/support/exceptions.py

BF+RF+ENH: minor fixups (styling, undefined vars/exceptions)

---

niceman/distributions/piputils.py

This PR makes a few cosmetic changes to code from #185 that @yarikoptic and I discussed.  I think the first commit (f553802c) is an obvious improvement, but I find the changes in the other two commits (4208d472, 9c962a6e) to be less readable than what's replaced.
Labeling as "WiP" because I think either the last two commits should be dropped or replaced with other suggestions.

Cosmetic followups to #185

---

niceman/base.py
niceman/distributions/base.py
niceman/distributions/conda.py
niceman/distributions/debian.py
niceman/distributions/docker.py
niceman/distributions/vcs.py
niceman/distributions/venv.py
niceman/resource/aws_ec2.py
niceman/resource/base.py
niceman/resource/docker_container.py
niceman/resource/shell.py
niceman/resource/ssh.py
niceman/support/distributions/debian.py
niceman/utils.py

Make default=None  the default in attrib; use attrib consistently

---

niceman/distributions/conda.py
niceman/distributions/piputils.py

Quick fixes #239, #238 
Let's see if anything is broken in the tests

lower case pip pkg name, rely on conda info for root location

---

.travis.yml
niceman/distributions/tests/test_vcs.py
niceman/distributions/vcs.py
niceman/tests/fixtures.py
niceman/tests/utils.py

NF: added GitRepo.root_hexsha

---

niceman/interface/base.py

BF(workaround): allow backends fail to import while preparing help

---

niceman/distributions/conda.py
niceman/distributions/venv.py

Trivial cleanup of a variable and method that are no longer used.

Clean up some unused things

---

niceman/distributions/base.py
niceman/distributions/tests/test_vcs.py
niceman/distributions/vcs.py

ENH: VCS: Make package file paths relative to repo root 

---

.travis.yml
niceman/distributions/singularity.py
niceman/distributions/tests/test_conda.py
niceman/distributions/tests/test_docker.py
niceman/distributions/tests/test_singularity.py
niceman/interface/retrace.py
niceman/resource/session.py
niceman/resource/singularity.py
niceman/resource/tests/test_session.py
niceman/resource/tests/test_singularity.py
niceman/tests/utils.py

This commit adds a resource class for singularity containers. (..and sneaks in a fix in the testing of Docker retracing)
The retracing of singularity containers is on hold while we investigate how to map containers back to their original image in a repository.
The installation of singularity was added to the Travis test setup.

ENH - Added resource for singularity containers.

---

niceman/resource/singularity.py

... for consistency with b836df19 (RF: Replace remaining attr.ib calls with attrib helper, 2018-05-25).
Re: #236
---
Minor cleanup.  Will merge once tests pass.

CLN: singularity: Replace attr.ib with attrib

---

niceman/resource/session.py
niceman/resource/ssh.py
niceman/resource/tests/test_session.py
niceman/resource/tests/test_ssh.py
niceman/support/paramiko_interactive.py

Changed SSH login code to use low level Paramiko Transport class

---

niceman/cmdline/helpers.py
niceman/cmdline/main.py
niceman/interface/__init__.py
niceman/interface/retrace.py
niceman/tests/test_cmdline_main.py

Fix grammar mistakes and simplify wording.

DOC: Revise text shown by 'niceman --help'

---

niceman/resource/aws_ec2.py
niceman/resource/tests/test_aws_ec2.py

BF: Fixed SSH connection to AWS resource

---

niceman/interface/ls.py

BF: do not fail `ls --refresh` if any of the resources failed to connect/query

---

niceman/resource/ssh.py

ENH: Added debug logging to display SSH connection parameters

---

niceman/distributions/debian.py

ENH: debian: Don't create an empty apt source file

---

niceman/resource/tests/test_base.py

TST: resource: Add regression test for 98fe13542

---

niceman/resource/ssh.py
niceman/resource/tests/test_ssh.py

First part of #340 
Will keep it separate from the second part so the password prompt can get into the impending point release.

BF: Added password prompt for SSH login

---

reproman/interface/delete.py
reproman/interface/ls.py
reproman/interface/tests/test_create.py
reproman/interface/tests/test_delete.py
reproman/interface/tests/test_ls.py
reproman/resource/base.py
reproman/resource/tests/test_base.py

Fixes #342 
Fixes #308 
- Added --force switch to the delete interface
- Added --refresh switch to the ls interface
- "Converted" the ResourceManager._save() method to public access by renaming to .save_inventory()

BF: Fixes to interface ls and delete

---

reproman/tests/test_installed.py

TST: Mark an expected failure on Travis

---

reproman/distributions/tests/test_debian.py
reproman/resource/base.py
reproman/resource/docker_container.py
reproman/resource/ssh.py
reproman/resource/tests/test_ssh.py

Please review individual commit messages for the descriptions
TODOs:
- ~~fix up singularity testing since there is no `'shub://vsoch/hello-world@42e1f04ed80217895f8c960bdde6bef4d34fab59'` any more~~ singularity will be handled separately (#406)

BF+ENHs: a collection of small tune ups/fixes

---

reproman/resource/singularity.py
reproman/resource/tests/test_singularity.py
reproman/support/external_versions.py

Note: it doesn't anyhow addresses fetching from shub:// urls with `@digest` (#406) which ideally we should get closure on IMHO from upstream.

Singularity 3.x compatibility fixes

---

reproman/interface/run.py
reproman/interface/tests/test_run.py
reproman/support/jobs/orchestrators.py
reproman/support/jobs/tests/test_orchestrators.py

This is a work-in-progress series that addresses gh-470 and partially addresses gh-469.

run: Extend --follow with optional stopping/deleting actions

---

reproman/resource/session.py

env -0 workaround where not available

---

reproman/support/jobs/job_templates/runscript/base.template.sh
reproman/support/jobs/submitters.py

See individual commits.
The last one -- I feel this might be of interest to other places as well were dynamic sleeping/reporting is desired, so might be generalized at some point.

ENH: make --follow "faster"

---

reproman/interface/run.py
reproman/interface/tests/test_run.py
reproman/support/exceptions.py

ENH: Raise a dedicated JobError if any subjob fails (in --follow mode only)

---

reproman/interface/run.py

Individual commits have more description

ENH: run --help output to use "path" for input/output + say "more than once" for appended

---

.travis.yml
reproman/support/jobs/job_templates/submission/local.template
reproman/support/jobs/orchestrators.py

According to gh-522, GNU parallel is more likely to be present on macOS.
Closes #522.

run: Switch to GNU parallel for local runscript

---

reproman/interface/tests/test_run.py
reproman/resource/session.py
reproman/resource/shell.py
reproman/resource/singularity.py
reproman/resource/ssh.py
reproman/resource/tests/test_session.py

Add recursion to get and put for local and ssh sessions

---

reproman/distributions/tests/test_venv.py

test_venv_identify_distributions() checks how links inside the virtual
environment are handled by identify_distributions().  On Travis, this
test has started to fail for the Python 3.8 build.  The last passing
run for the 3.8 build had Python 3.8.0, while the failure has 3.8.6.
failing: https://travis-ci.org/github/ReproNim/reproman/jobs/753369730
passing: https://travis-ci.org/github/ReproNim/reproman/jobs/745766696
The failing assertion is due to the layout in the environment not
meeting two expectations:
* We expect the paths of abc.py and machinery.py to be links to the
outside.
$ realpath $VENV/lib/python3.7/abc.py
/usr/lib/python3.7/abc.py
$ realpath $VENV/lib/python3.7/importlib/machinery.py
/usr/lib/python3.7/importlib/machinery.py
But when I test with Ubuntu 20.04 (Python 3.8.5), …

TST: venv: Adjust test for Python 3.8 and later

---

reproman/interface/execute.py
reproman/interface/tests/test_execute.py

See individual commits with more information and reasoning.

Use fixed rztracer and fix up the unittest for it to use another binary than ls
