- docs/source/glossary.rst
With some testing, setting the modline to 76 allows essentially the same behavior across vim, emacs and pyCharm (when the code width in pyCharm is set to 79 characters).  Why the difference of 3 characters? I believe that:
1. PyCharm adds spaces at the end of every line in the paragraph
1. PyCharm cuts off *before* 79 characters instead of *at* 79 characters
1. PyCharm starts counting at 1 instead of 0
Fun, eh?
> DOC: Update example modline for vim and emacs

- repronim/client/awsclient.py
- repronim/client/base.py
- repronim/client/dockerclient.py
- repronim/client/singularityclient.py
- repronim/client/sshclient.py
- repronim/client/tests/test_dockerclient.py
- repronim/cmdline/main.py
- repronim/environment/base.py
- repronim/environment/dockerenvironment.py
- repronim/environment/ec2environment.py
- repronim/environment/tests/test_dockerenvironment.py
- repronim/environment/tests/test_ec2environment.py
- repronim/environment/tests/test_localshellenvironment.py
- repronim/interface/base.py
- repronim/interface/create.py
- repronim/interface/install.py
- repronim/interface/ls.py
- repronim/resource.py
- repronim/support/exceptions.py
- repronim/tests/files/repronim.cfg
- repronim/tests/test_resource.py
This pull request includes:
1. Adding code to prompt the user for information if they don't have a key_name declared in their ec2-environment configuration.
2. Documenting the options in repronim.cfg at the top of the file in tests/files/repronim.cfg
3. After reading the first chapter of "Fluent Python", made chages to the Resource class to make it more Pythonic.
4. Enhanced error handling and user notices for command line options.
The unit testing of the new Ec2Environment.create_key_pair() method is beyond me at this point as it contains user prompts. Will work on that and bring it up at Monday's meeting to see if you have any thoughts on how to handle it.
My next step is to work on enhancing "repronim ls" and on allowing users to log directly into their environments through the …
> Added AWS SSH key creation

- repronim/environment/ec2environment.py
- repronim/resource.py
- repronim/tests/files/demo_spec1.yml
- avoid using `exit()` call directly.  Ideally we should come up with some dedicated exception for this situation
- check for empty key at any iteration
I still feel that we should allow to reuse existing key, but since function is `create_key_pair` I left that alone for now ;)
This one should finally Closes #42  ;-)
> ENH: EC2 key creation logic improvements

- niceman/retrace/packagemanagers.py
- niceman/retrace/rpzutil.py
was skimming through the code and decided to change a little -- better altogether to use our Runner helper so we have a central single point of interfacing with external commands.  Also IMHO better to not swallow blindly failed execution runs -- who knows what could have gone wrong
> RF: use our Runner for dpkg-query execution

- niceman/retrace/packagemanagers.py
- niceman/retrace/rpzutil.py
- niceman/retrace/tests/test_packagemanagers.py
- niceman/support/exceptions.py
- niceman/tests/test_utils.py
- niceman/utils.py
This update pulls origins into a separate configuration item.  For example, after retracing you will find a section that looks like:
```
origins:
- {archive: xenial, component: universe, label: Ubuntu, name: apt_Ubuntu_us.archive.ubuntu.com_xenial_0,
origin: Ubuntu, site: us.archive.ubuntu.com, type: apt}
- {archive: now, component: now, label: '', name: apt___now_0, origin: '', site: '',
type: apt}
- {archive: xenial, component: main, label: Ubuntu, name: apt_Ubuntu_us.archive.ubuntu.com_xenial_1,
origin: Ubuntu, site: us.archive.ubuntu.com, type: apt}
```
And packages now refer to the names within the origins:
```
packages:
- name: fsl-5.0-core
version: 5.0.9-3~nd16.04+1
candidate: 5.0.9-3~nd16.04+1
size: 8122764
architecture: amd64
md5: 310a086529df52f1291ba09cf9335dbe
sha1: …
```
> ENH: Pull out package origins into a separate configuration item

- niceman/retrace/packagemanagers.py
- niceman/retrace/tests/test_packagemanagers.py
To address #59 , I use the lower level apt_pkg python library to pull the archive_uri associated with an origin. This allows me to more accurately create the release file name, and pull the release file for local repositories.
To test, I created a repository with the alienblaster package:
```
mkdir /my
mkdir /my/repo
cd /my/repo
wget http://mirrors.kernel.org/ubuntu/pool/universe/a/alienblaster/alienblaster_1.1.0-9_amd64.deb
dpkg-scanpackages . >| Packages
apt-ftparchive release . >| Release
echo 'deb file:///my/repo ./' > /etc/apt/sources.list.d/local.list
apt-get update
apt-get install alienblaster
```
The resulting origin entry is:
```
- {name: apt____0, type: apt, component: '', label: '', site: '', archive_uri: 'file:///my/repo/',
archive: '', origin: '', date: '2017-02-21 …
```
> BF: Use ArchiveURI to identify local repositories

- niceman/retrace/packagemanagers.py
I adjusted the inner loop of _find_release_file so that it returns the Release file that matches the largest prefix of the source package filename.  The way it was before, if there was a smaller prefix that matched a Release file name, then it would use that instead.  For example: us.archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages could potentially match both us.archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease and us.archive.ubuntu.com_ubuntu_dists_InRelease (if they both existed).  But we want the longer one to be returned, not the shorter one.
> BF: Fixing search technique for the Release File Name

- .travis.yml
- niceman/interface/retrace.py
- niceman/interface/tests/test_retrace.py
- niceman/log.py
- niceman/retrace/packagemanagers.py
- niceman/retrace/rpzutil.py
- niceman/retrace/tests/test_packagemanagers.py
- niceman/retrace/vcs.py
- niceman/utils.py
Sits on top of @rbuccigrossi #58 
TODOs
It also
Future TODOs is to support
and refactor code accordingly
Also possibly
- For VCS types -- should we may be list only relative path names in files? then full paths should be easily reconstructable with a simple rule `if not isabs(path): fullpath = opj(pkg['path'], path)`?
- For full paths under '$HOME' -- I wonder if we should do analysis right away and convert them to use that (e.g. to make them '$HOME/blah' instead of '/home/yoh/blah' in my case)... and then record 'run' session and associate with tracking one which would contain value for HOME?
Sample output:
```shell
(git)hopa:~/proj/repronim/niceman[nf-git-trace]
$> niceman --dbg retrace ~/proj/repronim/niceman/README.md /home/yoh/deb/debs/imagezoom-ru-svn/trunk.upgraded/debian/changelog …
```
> NF: trace files belonging to VCS

- niceman/retrace/packagemanagers.py
- niceman/support/exceptions.py
Right now I'm experimenting with a DpkgOrigin class (using attr) as a drop-in replacement for the origin dict.  The next things are to tackle its conversion to a HashableDict (an attr object is already hashable) and then an OrderedDict (which is really used for YAML conversion).
> NF/WIP: DpkgOrigin class as a drop-in replacement for origin dict

- CONTRIBUTING.md
- setup.py
@chaselgrove please verify if this works for you ;)  (seemed to work on clean debian jessie)
> DOC: adjusted CONTRIBUTING to correspond to current state of requirements

- niceman/retrace/packagemanagers.py
- niceman/retrace/rpzutil.py
- niceman/retrace/tests/test_packagemanagers.py
- niceman/tests/test_utils.py
- niceman/utils.py
I still want to add unit tests for a couple of utility functions I added (safe_decode, safe_encode, and safe_write).
> BF: Fix for #83 to support Unicode filenames and package data

- .travis.yml
- tools/ci/build_install_apt
By default in bash, exit status of the sequence of commands separated with ; is as of the last
command executed.  So if any of then fail before then, shell would still report "all is ok", unless
1. you set -e   setting for the session (then would fail as soon as any command fails)
2. join them with  & instead of ;
Since our line got too long already, I just moved that installation into a script which should fail
if any step fails (see set -eux at the top)
Detected when saw decreased coverage within https://github.com/ReproNim/niceman/pull/85 which should havenot changed coverage that drastically
> BF(BK): moved installing of python-apt from source into a script to not mask failures to build it

- docs/source/cmdline.rst
- niceman/interface/__init__.py
- niceman/interface/login.py
- niceman/interface/start.py
- niceman/interface/stop.py
- niceman/interface/tests/test_create.py
- niceman/interface/tests/test_login.py
- niceman/resource/docker_container.py
- niceman/resource/tests/test_docker_container.py
- setup.py
This is not an actual pull request yet. Just sharing code.
The tty terminal replays all the commands run from a previous session when the container is restarted. Still figuring that one out.
To login to a docker container, first create it and then login (like so):
niceman create -r my-container -t docker-container
niceman login -r my-container
> Initial dockerpty setup

- niceman/interface/create.py
- niceman/interface/tests/test_create.py
- niceman/resource/aws_ec2.py
- niceman/resource/base.py
- niceman/resource/docker_container.py
- niceman/resource/shell.py
The --help output is not formatted very well.
niceman create --help
Otherwise, working well. The change was to add a --backend ArgParse command which takes multiple resource-specific config parmaters
e.g.
niceman create -r test1 -t docker-container --backend base_image_id=ubuntu:latest
> ENH: Moved resource specific create parameters to resource Class.

- niceman/interface/base.py
- niceman/interface/create.py
- niceman/interface/login.py
- niceman/resource/aws_ec2.py
- niceman/support/starcluster/__init__.py
- niceman/support/starcluster/exception.py
- niceman/support/starcluster/logger.py
- niceman/support/starcluster/progressbar.py
- niceman/support/starcluster/sshutils.py
- niceman/support/starcluster/static.py
- setup.py
Pull request for SSHing into AWS EC2 instance using StarCluster utils.
> ENH: Added StarCluster sshutils so users can log into AWS EC2 instances.

- .travis.yml
- tools/ci/build_install_apt
Starting August 1st, Travis defaults to using Ubuntu 14.04 instead of 12.04 for docker images. This broke our libapt build script.  Until we remove our dependency on python-apt, as a quick fix, I updated .travis.yml to use 12.04 again.
> BF: Get libapt build working on Travis

- niceman/resource/tests/test_ssh.py
- niceman/tests/test_tests_utils.py
continuation to #130 
immediate pros: no docker started unless actually needed
TODOs:
> SSH fixture - skips within before initiating docker, renamed

- niceman/conftest.py
- niceman/distributions/debian.py
- niceman/distributions/tests/test_debian.py
- niceman/support/distributions/debian.py
- niceman/support/distributions/tests/test_debian.py
- niceman/tests/test_utils.py
- niceman/utils.py
This branch bundles apt-cache, dpkg, and stat calls across multiple packages to speed up Debian identification. #142 
It reduces execution time of test_check_bin_packages() from 32 seconds to 2.1 seconds on my machine :)
One trick was to be able to carefully match up command results and the original list of packages. I end up placing the command results into a dictionary based on the package name (and package:arch for apt-cache and dpkg calls), and then loop through packages looking for matching results.
It's now ready for code review...
> WIP: Enhancement -  batch apt package commands

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
To address #151 - we check stderr for the warning on "-p", ask users to use Conda 4.3.19 or greater if the error occurs, and better handle the result so we don't crash (and detect as much as possible)
> BF: Detect and gracefully handle old conda versions

- niceman/interface/retrace.py
- niceman/interface/tests/test_retrace.py
Otherwise `niceman retrace` will fail to detect distributions when it
is given unnormalized paths like "$PWD/../niceman/setup.py" and
"/bin/../bin/ls".
Fixes #160.
> BF: retrace: Normalize paths before passing to tracers

- niceman/distributions/vcs.py
- niceman/interface/tests/test_retrace_packages.py
Ideally we might just make up a Remote(SpecObject) class, instead of
ad-hoc dict there and then it would not require custom checking there
Closes #105
> Do not store None values for url or pushurl

- niceman/distributions/conda.py
- niceman/distributions/piputils.py
- niceman/distributions/tests/test_conda.py
- niceman/distributions/venv.py
Adjust the conda tracer to reuse the batched `pip show` from the venv
tracer (#162).
Note that this is not ready to be merged because it depends on #162.
Currently this PR is against a temporary branch rather than master so
that the diff doesn't include the commits from #162.
> ENH+RF: Share 'pip {list,show}' code between venv and conda tracers

- niceman/distributions/vcs.py
#182 reports a failure in `test_git_repo_remotes`.  The error in that issue is an `AttributeError` that occurs because on failure `expect_fail=True` will result in None being returned, which we try to call `splitlines` on.
We, however, shouldn't actually expect an error there.  We know we're in a Git directory at that point because we have a hash.  Plus, `test_git_repo_remotes` is passing on Travis, so there has to be some difference causing the failure seen in #182.  I _think_ that is the fact that `lstrip` is a relatively recent addition to `git for-each-ref` (v2.13.0).
@chaselgrove, could you verify 1) your local Git version is pre v2.13.0 and 2) that `test_git_repo_remotes` now passes for you locally?
Closes #182.
> BF: vcs: Replace 'lstrip' with 'strip' for older Git version

- niceman/distributions/piputils.py
- niceman/distributions/tests/test_piputils.py
When multiple packages are passed to 'pip show', the entries for each package are separated by a line that contains the marker "---".  We split the output string on "---" to get the entries.  That, however, will break if an entry's field contains "---".  Instead use a regular expression to restrict the split to lines that consist only of "---".
Re: https://github.com/ReproNim/niceman/pull/168#discussion_r168196705
> BF: piputils: Be more selective when splitting show output

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
- niceman/resource/tests/test_shell.py
This does two things:
1. Addresses #187 - The latest release of conda does not put bin/conda in the environments. Therefore this pull request changes how we search for root paths for each environment.  We also remove the assumption that there is a conda and python version for each conda environment.
2. We now determine the name of the conda environment from the path (an issue identified in #174). An alternate approach is to use "conda-env info", but since we know the conda root path, we can save a shell call by analyzing the paths instead.
> BF+ENH: Support latest conda release and find conda environment names

- niceman/distributions/base.py
- niceman/distributions/conda.py
- niceman/distributions/piputils.py
- niceman/distributions/tests/test_conda.py
- niceman/distributions/tests/test_vcs.py
- niceman/distributions/tests/test_venv.py
- niceman/distributions/venv.py
- niceman/interface/retrace.py
- niceman/interface/tests/test_retrace.py
- niceman/tests/test_utils.py
- niceman/utils.py
From our pair-coding session with @kyleam earlier today:
moved to #189 
- ~~~unify multiple distribution entries in the retrace output~~~ moved to #184
> RF: multipass through Tracers

- niceman/distributions/conda.py
- niceman/distributions/piputils.py
- niceman/distributions/tests/test_conda.py
- niceman/distributions/tests/test_piputils.py
- niceman/distributions/tests/test_venv.py
- niceman/distributions/venv.py
- niceman/tests/utils.py
This PR fixes two issues:
* In 54da3757 I introduced a bug in conda traces that caused a duplicate pip listing for each conda package.
* Starting with 6762a746, I've abused "origin_location" to mean any location, but originally it was only used for locations of editable packages.  I've renamed "origin_location" to "location" and added a field "editable" that is True if the package is editable.
WIP because
Update: I've now added an editable package to the venv tests.
> Fix duplicate pip entry in conda trace; add "editable" attribute for conda/pip

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
This is a followup to #181, which modified the tracers to do multiple passes on the set of unknown files.  The venv tracer is currently the only tracer that will extend the set of unknown files that it passes back.  It does so if it encounters a pip package with a location that is outside of the virtualenv path, which happens in the case of system-wide installs as well as editable packages.
Make conda add editable pip packages to the unknown files.  Don't worry about system-wide packages because they aren't exposed in conda environments.
Closes #189.
> ENH: conda: Extend unknown files with editable pip packages

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
Since we already run conda --info, detecting the platform was surprisingly easy.  This addresses #195 .
> ENH: Detect conda architecture (platform) #195

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
This detects and gracefully handles when there are no custom packages installed in a conda environment (so that our search for *.json is empty).  This addresses #194 .
> BF: Gracefully handle no custom packages in a conda environment #194

- niceman/tests/fixtures.py
'git clone' sends it "Cloning into ..." message to stderr.
> TST: fixtures: Clone with expect_stderr=True

- niceman/distributions/tests/test_vcs.py
- niceman/distributions/vcs.py
For the most part, symbolic-ref's output will be the same as that of
rev-parse --abbrev-ref, but it's a bit nicer because 1) it will return
the current branch when we're on a branch without any commits and 2)
it won't return "HEAD" when we're in a detached state.
> ENH: vcs(git): Use symbolic-ref to get current branch

- niceman/cmdline/main.py
- niceman/config.py
- niceman/resource/base.py
- niceman/tests/fixtures.py
This PR
* Mentions the allowed config locations in `MissingConfigFileError`s message so that the user knows how to fix the problem.
* Mentions `$PWD/.niceman/config` in the locations list.
* Corrects the documented location of the config file in `XDG_CONFIG_HOME`.
* Changes the `XDG_CONFIG_HOME` location from `$XDG_CONFIG_HOME/niceman/niceman.cfg` to `$XDG_CONFIG_HOME/niceman/config` for consistency with other names.
> DOC:  Improve documentation and reporting of config locations

- niceman/distributions/base.py
- niceman/formats/tests/test_niceman.py
NicemanProvenance is unable to load a spec that includes a
GitDistribution or SVNDistribution because these don't follow the
expected naming conventions.  Specifically, GitDistribution and
SVNDistribution are in the module "vcs" rather than "git" and "svn",
respectively, and the "SVN" in SVNDistribution is all uppercase.
We could (1) adjust Distribution.factory to treat SVN and Git as
special cases, (2) restructure things so that the SVN and Git follow
the expected naming pattern, or (3) maintain a mapping from
distribution["name"] -> module.class.
Go with (1) for now because it involves the fewest changes.
Fixes #222.
> BF: Add kludge to load Git and SVN distributions

- niceman/resource/tests/test_ssh.py
The 'apt-get install bc' call is currently failing with "Unable to
locate package bc".
I'm guessing this is because the rastasheep/ubuntu-sshd:14.04
Dockerfile now removes /var/lib/apt/lists.  See aaf4e12 (Added Cleanup
layers for the containers, 2018-05-02) in the rastasheep/ubuntu-sshd
repo.
Fixes #229.
> BF+TST: Add 'apt-get update' call to test_ssh_class

- niceman/distributions/debian.py
- niceman/distributions/tests/test_debian.py
- niceman/support/distributions/debian.py
- niceman/support/distributions/tests/test_debian.py
* Don't warn about  "multiple packages" when the path is a directory because the Debian tracer doesn't handle directories and these warnings flood the screen.
* Fix "multiple package" test to remove false positives.
Fixes #224.
> debian: Improve warning about multiple packages found by dpkg-query -S

- niceman/distributions/vcs.py
Use 'git branch' rather than a plumbing command for compatibility with
older gits.  --contains has been available via 'git branch' since
v1.5.4, but the option was only introduced to for-each-ref in v2.7.0.
Fixes #237.
> BF: git: Get remote branches with 'branch' not 'for-each-ref'

- niceman/formats/reprozip.py
- niceman/interface/common_opts.py
- niceman/interface/exec.py
- niceman/interface/retrace.py
- niceman/interface/tests/test_exec.py
- niceman/log.py
- niceman/resource/docker_container.py
- niceman/resource/session.py
- niceman/resource/tests/test_session.py
- setup.py
Here's the first pass of @yarikoptic's and my attempt to hook up reprozip's tracer to `niceman exec`.
To try this out
* checkout the extract-c-tracer branch from https://github.com/ReproNim/reprozip
* `cd  reprozip/native && make`
Then you can run `niceman exec` with the `--trace` argument.  Since we haven't deposited the binary anywhere, you can use the temporary `--tracer` option to point to the binary in the reprozip/native directory.
> Prototype for exec --trace

- .travis.yml
As expected, the tests fail on these branches.
> TST: travis: Don't build third-party branches

- niceman/distributions/conda.py
- niceman/distributions/tests/test_conda.py
Conda's installation code originally handled packages and channels as
dicts because NicemanProvenance stopped converting dicts to objects at
that depth.  This is no longer the case as of 3b8a9884 (RF+BF: read
spec recursively, 2018-05-07).
> BF: conda install: Work with packages and channels as SpecObject's

- niceman/distributions/tests/test_docker.py
As recent test failures show (gh-254), this isn't the case.
Break apart test_docker_trace into two tests.  The first pulls by a
tag and traces the image, making no assumptions about the actual IDs.
The second pulls by the digest so that we can make assertions with
known IDs.
Also, temporarily disable assertions about the tags of installed
"packages" because these repo tags won't be present if another local
image is already has with that tag (e.g., an updated alpine@3.6).
This approach should eliminate failures due to changing IDs as long as
the untagged repo digests remain available on DockerHub.  However, we
should eventually generate/upload our own test images so that we can
control the image tags.
Re: #203
Closes #254.
> TST: docker: Don't assume that tags map stably to image IDs

- niceman/distributions/tests/test_vcs.py
- niceman/distributions/vcs.py
This adds basic support for instantiating Git repositories listed in a
GitDistribution object.  If a repository isn't present, we clone it
from one of the recorded sources.  Otherwise, if the recorded revision
isn't present, we fetch a remote that is marked as containing that
revision.  GitDistribution.install_packages' main goal is to check
out the same revision, but it also sets up the recorded remotes and
checks outs the recorded branch if possible.
~Right now the tests only cover the simpler cases.~
---
> NF: Add initial support for "installing" Git repositories 

- niceman/distributions/tests/test_vcs.py
When this test was originally added, there was only one remote, so it
was deterministic.  But a following commit added a second remote with
a dead url, and we can't use that one to clone the repo.
Fixes #259.
> BF+TST: vcs: Fix flaky test_git_install_add_remotes

- niceman/distributions/tests/test_venv.py
- niceman/distributions/venv.py
- niceman/tests/test_utils.py
- niceman/utils.py
Add support for installing non-editable, local packages.
Some current limitations:
* If a virtualenv directory already exists at a path, running "install" can upgrade/downgrade the packages in the spec to the recorded version, but that's all.  There is no check of the python version or whether the environment has additional packages.
* We don't handle system or editable packages.
Both of these issues involve components outside of the virtualenv distribution, so to address them we'd need to define a way for the installation procedures of different distributions to interact.
> NF: venv: Add basic support for installation 

- niceman/distributions/piputils.py
- niceman/distributions/tests/test_piputils.py
- niceman/distributions/tests/test_venv.py
- niceman/distributions/venv.py
```
We use the legacy format of 'pip list' because the legacy format
contains an extra location field for editable packages.  Using
'--format=json --verbose' doesn't provide the same information: pip
<10.0 doesn't include locations at all, and pip >=10.0 does include
locations, but unlike in the legacy output, every package has a
location, so the json output can't be used to identify editable
packages.
However, as of pip 18.0 (2018-07-22), 'pip list' no longer supports
'--format=legacy'.  Instead, make another call to pip to retrieve a
list of editable packages to use to set the 'editable' attribute.
```
Fixes #271.
>  BF: piputils: Rework approach for pip 18.0 compatibility

- niceman/interface/exec.py
- setup.py
At the moment NICEMAN functionality on systems other than GNU/Linux
ones is fairly limited and untested, but we intend to support other
systems, so we can't list ReproZip as an unconditionally requirement.
Fixes #276.
---
This hits a branch of code that needs test coverage, but I don't see a reason to hold this up for it.
> Restrict reprozip dependency to Linux

- niceman/distributions/debian.py
- niceman/distributions/tests/test_debian.py
- niceman/tests/test_utils.py
- niceman/utils.py
After a recent system update, `test_debian.py:test_utf8_file` is failing locally for me.  That test is designed to not assume that the "*.crt" file exists, but it still fails because of `get_details_for_packages` can't handle an empty list.
>  BF: DebTracer.get_package_details: Handle empty package list

- niceman/interface/exec.py
This is a leftover from 68776b88 (ENH: Added mkdir, get and put
interfaces, 2017-10-11).
> DOC: Update stale exec summary

- niceman/interface/base.py
- niceman/interface/login.py
- niceman/resource/base.py
- niceman/resource/tests/test_base.py
When `create` is given a backend parameters, but the resource doesn't have parameters or the given parameter doesn't match, we showed
```
2018-09-11 13:33:43,032 [ERROR  ] Bad --backend parameter 'imagee' [base.py:backend_set_config:53] (NotImplementedError) 
```
Resource without parameters:
```
$ niceman create -t shell shellbert -b imagee=foo 
2018-09-11 13:29:49,342 [ERROR  ] Resource type 'shell' has no known parameters [base.py:backend_set_config:80] (ResourceError) 
```
Resource has parameters, but nothing close to what was given:
```
$ niceman create -t docker-container dockerbert -b not-even-close=foo
2018-09-11 13:31:04,455 [ERROR  ] Bad --backend parameter 'not-even-close'
|   Known backend parameters:
|     engine_url (Docker server URL where engine is listening for …
```
> ENH: Suggest backend parameters when an unknown value is given

- niceman/resource/singularity.py
```
Pass expect_fail=True to the runner calls to prevent methods like
exists() from unnecessarily worrying the user with things like
[ERROR  ] stderr| cat: /no/such/file: No such file or directory
Using expect_fail=True here is consistent with
ShellSession._execute_command().
```
> ENH: singularity: Expect failures when running commands

- niceman/interface/create.py
- niceman/interface/tests/test_create.py
- niceman/resource/base.py
- niceman/resource/ssh.py
- niceman/resource/tests/test_base.py
-   Pass backend parameters when instantiating the resource classes so that we can declare parameters as required.
-   Mark ssh's `host` as mandatory.
Fixes #300.
(Update: Just realized that 8466f0e also fixes #299.)
---
Are there any other attributes that should be mandatory?
>  ENH: Support required backend parameters

- niceman/resource/tests/test_session.py
```
Adjust the resource_session fixture to delete singularity instances so
that they don't pollute the user's list of running instances.  Without
this, each run of test_session_abstract_methods with
SingularitySession adds entries like
$ singularity instance.list
DAEMON NAME      PID      CONTAINER IMAGE
70ee38d1a70      21382    /tmp/.singularity-runtime.EcWxJv4l/python:2.7
e9eed6fafdb      20911    /tmp/.singularity-runtime.zeQVjAch/python:2.7
```
>  TST: resource: Prevent proliferation of Singularity instances

- niceman/resource/docker_container.py
- niceman/resource/session.py
- niceman/resource/shell.py
- niceman/resource/singularity.py
- niceman/resource/ssh.py
- niceman/resource/tests/test_session.py
This mostly addresses #295, but it looks like the particular example that issue gave still won't work because `AwsEc2` doesn't define a `get()` method.
---
>  ENH: resources: Teach get/put to infer destination basename 

- niceman/interface/exec.py
- niceman/resource/singularity.py
- niceman/resource/tests/test_singularity.py
Fixed 2 issues with the singularity resource:
1. When creating a new singularity resource, the name and id of the resource were getting the same value which is problematic when retrieving the resource config info.
2. Unsightly and false-positive ERROR messages were being displayed from the singularity get_instance_info() method.
> BF: Fixed issues with creating a singularity resource

- niceman/interface/__init__.py
- niceman/interface/backend_parameters.py
- niceman/interface/base.py
- niceman/interface/create.py
- niceman/interface/tests/test_backend_parameters.py
- niceman/interface/tests/test_create.py
Rather than 
```
Usage: niceman create [--version] [-h]
[...]
-b BACKEND [BACKEND ...], --backend BACKEND [BACKEND ...]
One or more backend parameters in the form KEY=VALUE.
Options are: "access_key_id" (AWS access key for
remote access to your Amazon subscription.), "image"
(AWS image ID from which to create the running
instance), "instance_type" (The type of Amazon EC2
instance to run. (e.g. t2.medium)), "key_filename"
(Path to SSH private key file matched with AWS key
name parameter.), "key_name" (AWS subscription name of
SSH key-pair registered.), "region_name" (AWS
availability zone to run the EC2 instance in. (e.g.
us-east-1)), "secret_access_key" (AWS secret access
key for remote access to your Amazon subscription),
"security_group" (AWS security group to assign to the
EC2 …
```
> List backend parameters with command rather than as unformatted block

- niceman/resource/base.py
Usually importing a resource fails because the user has passed an
unknown resource type, so we report the known resources in the
exception message.  But if the import of a known resource fails (e.g.,
because the resource imports an uninstalled module), it's confusing to
show a list of known resources.
Closes #297.
> ENH: Don't list resources if loading a known resource fails

- niceman/interface/create.py
- niceman/interface/tests/test_create.py
The command line arguments will come in as a ["key=value"] list, but
we should recognize a mapping so that niceman.api.create() callers
aren't forced to construct a list.
Closes #312.
> ENH: create: Teach parse_backend_parameters how to handle a mapping

- niceman/distributions/redhat.py
test_redhat.py::test_tracer is failing on Travis with
TypeError: __init__() got an unexpected keyword argument 'excluded'
Presumably this is due to a change in the Docker image used for this
test.
Instead of dying in such a situation, issue a warning that we've
encountered an unknown field in the 'yum --verbose repolist' output
and continue.  Perhaps we should add an "excluded" attributes to
RPMSource and/or update the test to use a stable Docker image, but we
should still make _find_all_sources resilient to unknown keys to avoid
such failures in the future.
> BF: redhat: Don't instantiate RPMSource with unknown fields

- niceman/distributions/tests/test_debian.py
- niceman/formats/tests/test_niceman.py
- niceman/interface/tests/test_retrace_packages.py
- niceman/resource/tests/test_docker_container.py
- niceman/resource/tests/test_shell.py
All of these appear to be meant manual debugging and don't affect the
actual tests.  Remove them so that they don't pollute the test output.
This becomes more important as of 3ef0f5c0 (Added -s switch for pytest
in travis, 2018-09-13) because the test stdout/stderr is dumped to the
Travis logs, making the logs exceed Travis's online display limit.
Closes #322.
> CLN+TST: Purge print statements in tests

- niceman/interface/__init__.py
- niceman/interface/execute.py
- niceman/interface/tests/test_execute.py
```
"exec" is a poorly chosen name because it conflicts with the `exec`
statement in Python 2.  Things like
python2 -c "import niceman.api.exec"
python2 -c "from niceman.api import exec as nm"
python2 -c "import niceman.interface.exec as nm_exec"
all fail with syntax errors.
```
I ran into this with #324.  This needs to be resolved in order to handle the Python 2 test errors there.
> BF+RF: interface: Rename "exec" to "execute"

- niceman/resource/session.py
- niceman/resource/singularity.py
- niceman/resource/ssh.py
- niceman/resource/tests/test_session.py
- niceman/utils.py
Main changes: 
* Make it possible to use string commands with SSHSession because this is possible with other sessions and used by internal callers of execute_command().
* Provide better escaping for commands in SSHSession and SingularitySession.
* Provide better escaping for session methods like isdir().  This is unrelated to the initial purpose of this PR, but it was needed for adding the string/list command form tests to test_session_abstract_methods().
> BF: Update SSHSession to handle string command

- niceman/distributions/tests/test_debian.py
- niceman/distributions/tests/test_redhat.py
This has been deprecated since pytest 3.7 [0] and leads to an
error (by default [1]) starting with pytest 4.
Fixes #333.
[0]: https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
[1]: https://docs.pytest.org/en/latest/changelog.html#removals
> TST: Don't call pytest fixtures directly

- niceman/interface/base.py
- niceman/support/param.py
- niceman/tests/test_api.py
- niceman/utils.py
inspect.getargspec() was deprecated in Python 3, briefly removed
entirely, and then restored in 37dc2b2883 (Issue #25486: Resurrect
inspect.getargspec in 3.6. Backout a565aad5d6e1., 2016-01-11).
Much if not all of the code we're updating came from DataLad via 3rd.
DataLad has since dealt with this issue.  Add our own compatibility
function because merging in the relevant DataLad bits would require a
lot of work at this point.
> MNT: Avoid use of deprecated inspect.getargspec()

- niceman/distributions/base.py
- niceman/distributions/vcs.py
- niceman/formats/base.py
- niceman/resource/base.py
- niceman/support/protocol.py
- niceman/ui/base.py
The key patch is 50deea04 (BF: Declare abc.ABCMeta in py3-compatible way).
> Adjust ABCs to be Py3-compatible

- niceman/interface/tests/test_execute.py
```
There are two issues with this condition: (1) it was intended to say
"not in" rather than "in" and (2) an ExternalVersions instance's
__contains__(item) always returns False if __getitem__(item) hasn't
been called previously.  The combination of no. 1 and no. 2 means the
test would never be skipped.
No. 2 has been fixed as of DataLad's e71a57aa3 (BF: external_versions:
Make __contains__ work with non-primed items, 2018-12-03) and has been
incorporated via 3rd.
Update the skipif condition accordingly.
```
>  TST: execute: Fix skipif condition

- niceman/interface/ls.py
- niceman/interface/tests/test_sequence.py
- niceman/resource/shell.py
also state "available" for localshell
> BF: do not blow `ls` when status is None

- niceman/distributions/debian.py
- niceman/distributions/tests/test_distribution.py
- niceman/resource/ssh.py
- niceman/resource/tests/test_session.py
- ssh: Would fall to try running command via `sudo` (eventually we should make it configurable/interactive, for now - just a "feature") if permission denied upon initial run
- probably should be RFed anyways to be generic across different backends (e.g. shell etc)
- partially addresses #351 
- Also makes possible to pass (needed) noninteractive DEBIAN_FRONTEND env variable
> ENH: crude attempt to make "install" work when sudo needed

- niceman/resource/aws_ec2.py
A string is an acceptable form [*], but using a string rather than a
list leads to an error when fabric merges a configured IdentityFile
value from ssh_config (a fix is proposed in fabric/fabric#1924).
[*] http://docs.fabfile.org/en/2.4/api/connection.html#connect-kwargs-arg
> BF: aws_ec2: Pass key_filename as a list

- niceman/resource/base.py
- niceman/resource/tests/test_base.py
Resource IDs are often long and unwieldy to type.  Make it possible to
match them by giving a unique prefix (à la git hexsha matching).
Don't bother with supporting partial matching for names because a name
should already serve as a short label (like a branch name, to continue
the git analogy).
Closes #307.
Supersedes #330.
> NF: resource: Support partial matches on ID

- setup.py
Fixes #365.
---
The last commit temporarily adjusts Travis to run `reproman test`.  I want to see if it passes but plan to drop it afterward.
Check I ran to see if the data files got installed as expected:
```
(codebase)% git ls-files reproman | grep -v \.py$ | sort >/tmp/from-repo
(site-packages of virtualenv)% find reproman -type f | grep -v '\.pyc\?$' | sort >/tmp/from-site-packages
% diff /tmp/from-repo /tmp/from-site-packages && echo same
same
```
> BF: setup.py: Install data files

- reproman/distributions/tests/test_venv.py
- reproman/distributions/venv.py
We resolve virtualenv symlinks and report them as unknown files
because links in the virtual environment may point to system
packages ($ENV/lib/python3.5/types.py -> /usr/lib/python3.5/types.py),
and we want to detect those resolved paths with another
tracer (usually DebTracer) on the next `retrace` iteration.
However, a symlink may point to another file under the same virtual
environment, as is the case with "$ENV/bin/python -> $ENV/bin/pythonX"
links.  Returning the resolved path of an internal link as an unknown
file to `retrace` will result in a duplicate [*] virtualenv
distribution because the path will reach the virtualenv tracer on the
next iteration.  (This can in turn lead to duplicate Git distributions
if any of the virtualenv packages are editable.)
Re: #367
[*]: Or at least …
> BF: virtualenv: Don't return internal symlinks as unknown paths

- .travis.yml
- reproman/distributions/tests/test_conda.py
- reproman/distributions/tests/test_debian.py
- reproman/distributions/tests/test_docker.py
- reproman/distributions/tests/test_redhat.py
- reproman/distributions/tests/test_singularity.py
- reproman/distributions/tests/test_venv.py
- reproman/interface/tests/test_execute.py
- reproman/interface/tests/test_retrace.py
- reproman/interface/tests/test_sequence.py
- reproman/resource/singularity.py
- reproman/resource/tests/test_docker_container.py
- reproman/resource/tests/test_session.py
- reproman/resource/tests/test_singularity.py
- reproman/resource/tests/test_ssh.py
- reproman/support/external_versions.py
- reproman/support/tests/test_external_versions.py
- reproman/support/tests/test_globbedpaths.py
- reproman/tests/fixtures.py
- reproman/tests/skip.py
- reproman/tests/test_cmd.py
- reproman/tests/test_protocols.py
- reproman/tests/test_skip.py
- reproman/tests/test_tests_utils.py
- reproman/tests/test_utils.py
- reproman/tests/utils.py
The goal of this PR is to make it easier to add custom skip functions.  (I started looking at this when working on adding a custom "skip if condor not installed" function.)  I've added a new module tests/skip.py that defines two entry points, `skipif` and `mark`.  These provide access to all the conditions.  For example, for the no network case, it'd look something like
```python
@mark.skipif_no_network
def test_some_network():
pass
```
or
```python
def test_some_thing():
[...]
if [some on-the-fly reason to skip]:
skipif.no_network()
```
Those `skipif.*` and `mark.skipif_*` functions above are defined based on a single function, which is  member of the list of functions in `skip.CONDITION_FNS`:
```python
def no_network():
return ("no network settings", …
```
> Add new module for defining test skip conditions

- reproman/interface/ls.py
- reproman/interface/tests/test_ls.py
```
% reproman ls
RESOURCE NAME        TYPE                 ID                  STATUS    
-------------        ----                 --                  ------    
sm                   ssh                  cdfd149d-4288-4c64- N/A       
ss                   shell                5138c6e4-35eb-11e9- available 
ubdock               docker-container     d57fbb52c704bd6b0b4 running   
Use --refresh option to view updated status.
% reproman ls ubdock
RESOURCE NAME        TYPE                 ID                  STATUS    
-------------        ----                 --                  ------    
ubdock               docker-container     d57fbb52c704bd6b0b4 running   
Use --refresh option to view updated status.
% reproman ls cdfd ss
RESOURCE NAME        TYPE                 ID …
```
> ls: Support limiting output to specified resources

- reproman/distributions/tests/test_redhat.py
- reproman/distributions/tests/test_vcs.py
- reproman/tests/fixtures.py
Clean up a few places that log expected stderr as errors.  For example, there is no need to pollute the test logs with
[ERROR  ] stderr| Switched to branch 'master'
> TST: Demote some log errors

- reproman/resource/ssh.py
These are presumably pastos from when the ssh resource was created.
> DOC: ssh: Clean up misplaced AWS-related bits

- reproman/distributions/tests/test_venv.py
- reproman/distributions/venv.py
- reproman/interface/retrace.py
- reproman/tests/test_utils.py
- reproman/utils.py
When pyc files come in, convert them to the non-cached name because this is what can be associated with packages (both virtualenv and system).  The approach as of this PR's 4ca6ff47f isn't sufficient because it covers only the virtualenv package case.  If the pyc file is part of the system's python distribution, it will pass it back out as an unknown file, and DebTracer won't detect it.
In order to deal with this, we need to do two things to unknown files that are subpaths of the virtualenv: (1) apply the pyc -> py mapping over them and (2) widen the symlink resolution to handle cases where the leading path has a directory symlink (e.g.,  `$VENV/lib/python3.5/encodings -> /usr/lib/python3.5/encodings`).
> retrace: Map pyc files back to their source

- reproman/resource/ssh.py
Using paramiko currently floods our output with warnings like
[...]/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:39:
CryptographyDeprecationWarning: encode_point has been deprecated on
EllipticCurvePublicNumbers and will be removed in a future
version. [...]
Silence these because there's nothing for us to do here besides wait
for a paramiko release that includes a fix.  Leave a comment pointing
to the currently open paramiko PR that deals with these warnings.
Closes #390.
> MNT: ssh: Silence paramiko warnings

- reproman/distributions/debian.py
- reproman/resource/docker_container.py
- reproman/resource/ssh.py
- reproman/support/jobs/template.py
- reproman/tests/test_api.py
Otherwise it affects our startup time due to import of all the interfaces. Seems to shorten generic `--help` from >700ms to <500ms on my laptop. notably more responsive.  Also `reproman.api` import becomes only ~200 ms, from ~550ms.
See https://github.com/ReproNim/reproman/issues/397
for a more generic description of the issue and possible remedies.
I also have implemented a [basic ugly prototype for lazy loading of `yaml` module API](https://github.com/yarikoptic/ReproNim/compare/fda9c5184b668a178eba420974d54f8c8ca2fff8...opt-imports), since by itself it takes ~100 sec and for us would shave off ~40ms. BUT it is too ugly, and if we decide to go that way, we better generalize it for any module (e.g. `json` is one of the other ones).
TODOs:
> OPT: delay imports of requests, jinja2, paramiko (et al) until used

- reproman/resource/ssh.py
When the inventory contains a password-protected resource, calling
`niceman ls --refresh` will display a "Password: " prompt _before_
displaying the line for the resource.  Add the resource name to the
prompt so that users know what they are entering a password for.
For operations that work on a single resource (e.g., login), this
added information isn't useful, but it also doesn't hurt.
Re: #400
> ENH: ssh: Include resource name in password prompt

- reproman/distributions/conda.py
- reproman/formats/reproman.py
- reproman/interface/run.py
Calling yaml.load() without explicitly defining the Loader is
deprecated as of PyYAML 5.1.  The more restrictive and safer variant,
which we already use in some spots, should be sufficient for our
purposes.
See <https://pyyaml.org/wiki/PyYAMLDocumentation#loading-yaml>.
> MNT: Consistently use yaml.safe_load()

- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
DataLad dropped {Git,Annex}Repo.is_dirty() in 077de16ff (RF: Retire
`Repo.is_dirty()`, 2019-04-13).  Instead of is_dirty(), use GitRepo's
dirty property, which still exists in the latest DataLad.  This should
give the same results because is_dirty() is called without arguments
in all these spots.
> MNT: orchestrators: Avoid DataLad's is_dirty()

- reproman/support/external_versions.py
- reproman/tests/skip.py
There's no reason to add a custom "cmd:" variant when we can inspect
at the version from the python module.
> RF: external_versions: Drop cmd:datalad

- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
Adjust the local shell prepare_remote() procedure to check out the target *after* an existing remote dataset is updated.
>  BF: orchestrator: Fix target commit checkout for shell resource

- .travis.yml
The REPROMAN_TESTS_NONETWORK run is hanging on the 'route add'
command (see gh-420).  The reason for this isn't clear, but let's
follow DataLad (where this setup is inherited from) and remove these
commands.  See DataLad's 64a4dd7aa (Remove messing with the route
table -- not sure how/if it works currently, 2016-09-15).
> TST: travis: Remove 'route' commands for NONETWORK run

- reproman/distributions/singularity.py
$> REPROMAN_LOGLEVEL=1 python -c 'from reproman import lgr; lgr.debug(ValueError("kaboom"))'
2019-05-23 13:49:11,631 [Level 5] Instantiating config
2019-05-23 13:49:11,638 [DEBUG  ] Reading files: ['/etc/reproman/reproman.cfg', '/etc/xdg/reproman/reproman.cfg', '/home/yoh/.config/reproman/reproman.cfg', '.reproman/reproman.cfg']
2019-05-23 13:49:11,642 [Level 5] Done importing main __init__
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
msg = self.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
return fmt.format(record)
File "/home/yoh/proj/repronim/reproman/reproman/log.py", line 141, in format
if record.msg.startswith('| '):
AttributeError: 'ValueError' object has no attribute …
> BF: exception cannot be logged, preceding debug() already logs its exc_str

- reproman/distributions/tests/test_debian.py
- reproman/distributions/tests/test_vcs.py
- reproman/distributions/tests/test_venv.py
- reproman/interface/tests/test_retrace.py
- reproman/tests/utils.py
/bin/ed was found to be absent on real-life systems (apparently not that many
tools depend on good old ed).
iptables is being deprecated by nftables, and exists as a symlink/alternative
on Debian systems. Unfortunately we do not even track alternatives ATM (ref #102)
Closes #423
> RF: use /bin/bash instead of /bin/ed or /sbin/iptables, define centrally

- reproman/interface/run.py
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
- tools/ci/install_datalad
We grab the datalad-containers information from the dataset's config,
but this approach only works for containers in the current dataset.
To support containers in subdatasets, we can instead retrieve the
container information with datalad-container's (relatively new)
find_container() helper.
---
> run: Adjust container job parameter to work with subdatsets

- reproman/tests/skip.py
- reproman/tests/test_skip.py
```
Within Mark.__getattr__(), an AttributeError can be raised either
because the specified condition function (i.e. mark.skipif_FN) does
not exist or because the condition function itself raises an
AttributeError.  We didn't consider the latter, leading to confusing
error messages about skipif_FN not existing when FN raises an
AttributeError.
Distinguish the two cases above by adjusting Namespace to raise a
Namespace-specific subclass of AttributeError when it can't find a
condition function.
```
Fixes #429.
> BF: skip: Don't swallow AttributeError's from condition functions

- .travis.yml
- CONTRIBUTING.md
- reproman/distributions/tests/test_venv.py
- reproman/distributions/venv.py
VenvPackage has a local attribute that is set to true if the package
is a local package (as classified by 'pip list --local'), so if
someone wanted to determine whether the environment was created with
--system-site-packages, they could inspect VenvEnvironment for any
packages without local=True.  But this is tedious to do by visual
inspection.  Plus we plan to add support for pruning packages without
files, in which case inspecting the environment object after the fact
would no longer be a reliable way of knowing that
--system-site-packages was used.
Add a VenvEnvironment attribute that explicitly marks whether the
environment has non-local packages.
Closes #428.
> ENH: VenvEnvironment: Add system_site_packages attribute

- reproman/distributions/tests/test_singularity.py
- reproman/resource/singularity.py
- reproman/resource/tests/test_singularity.py
- reproman/tests/fixtures.py
This PR includes various fixes and touch-ups to `{resource,distribution}/singularity.py` and their tests.  The more notable ones:
* Fix IndexError when creating a Singularity resource and there are existing instances.
* The Singularity resources image attribute is now required (rather than defaulting to None, which wasn't handled).
* Testing should now work with Singularity v3, with one expected failure due to gh-406.
* test_singularity_resource_class tries harder to clean up its test instances on failure and to not collide with existing instance names.
> Singularity fixes and testing improvements

- .travis.yml
- reproman/tests/test_utils.py
As explained in c3ee9349c (TST: travis: Expose system packages for
virtualenv tests, 2019-06-05), the REPROMAN_TESTS_ASSUME_SSP build
needs to be matched up with the default Python version on Travis.
The default distribution for Travis has recently changed from Trusty
to Xenial, so the py3.4/REPROMAN_TESTS_ASSUME_SSP is failing [0].  Use
py3.6 for the REPROMAN_TESTS_ASSUME_SSP, which should come built
in.  (And switch the existing py3.6 run to py3.4 so that we still have
a run for 3.4, which we claim to support.)
[0]: https://travis-ci.org/ReproNim/reproman/jobs/545343359#L194
> TST: travis: Use py3.5 for REPROMAN_TESTS_ASSUME_SSP build

- reproman/interface/backend_parameters.py
- reproman/interface/create.py
- reproman/interface/tests/test_backend_parameters.py
- reproman/resource/base.py
- reproman/resource/tests/test_base.py
This PR corrects spots where we output an unusable, underscore-delimited resource type instead of a hyphenated one (e.g., docker_container instead of docker-container).  It also improves the error message when a underscore-delimited form is used.
> BF: Correct reported resource types

- reproman/distributions/debian.py
- reproman/distributions/docker.py
- reproman/distributions/redhat.py
- reproman/distributions/singularity.py
It is not clear if we really had to disable `cmp` which hinders simple comparison of our objects.  
Having some tests still failing locally (yet to troubleshoot), submitting to CI
> RF: revert to default cmp=True for attr.s. Rely on frozen to get hash generated

- reproman/conftest.py
- reproman/resource/base.py
- reproman/resource/tests/test_aws_ec2.py
- reproman/resource/tests/test_base.py
- reproman/resource/tests/test_docker_container.py
- reproman/resource/tests/test_shell.py
- reproman/resource/tests/test_ssh.py
If we encounter an invalid parameter when instantiating resources from the inventory, issue a warning and filter out the parameter rather than raising a `ResourceError`.
Closes #171.
> ENH: resource: Tolerate unknown resource parameters in inventory

- reproman/distributions/tests/test_singularity.py
- reproman/resource/tests/test_singularity.py
- reproman/support/jobs/tests/test_orchestrators.py
Singularity Hub has been down for a while.  Mark the tests that fail
because of this as expected failures so that we don't have to look
into each Travis build to make sure that the only failures are the
Singularity Hub-related tests.
> TST: Mark failures due to offline Singularity Hub as expected

- reproman/tests/test_utils.py
- reproman/utils.py
`run` and `create` use parse_kv_list() to parse key-value pairs
provided on the command line.  If a caller doesn't use the expected
"key=value" form, we fail unhelpfully within parse_kv_list():
dictionary update sequence element #0 has length 1; 2 is required
Say
Expected 'key=value' format but got 'blahbert'
instead.
> parse_kv_list: Improve error message for invalid key=value pair

- reproman/distributions/conda.py
- reproman/distributions/tests/test_conda.py
Our test suite is failing with the latest miniconda version (gh-443).
The initial issue looks to be a version conflict.  A reasonable
approach would be to just bump all versions in that test because
understanding or resolving this specific set of incompatibilities
between old software versions isn't worth the time or effort.
But that won't work because our distributions.conda isn't compatible
with the latest conda in at least two ways.  We use an environment
file that doesn't have an extension that conda now expects.  That's an
easy fix, and there's a patch in gh-443.  The bigger issue is that
environments seem to no longer have their own bin/conda unless conda
is explicitly installed in the environment.  (This mirrors the then
seemingly hard-to-trigger problem initially described in …
> BF: conda: Temporary pin version in miniconda URL

- .travis.yml
- reproman/resource/ssh.py
- tools/ci/prep-travis-forssh-sudo.sh
- tools/ci/prep-travis-forssh.sh
Doing so will allow us to test `run`, in particular the set prepartion
and state management of DataLad datasets over SSH, without needing to
go through a Docker container.
The tools/ci/ scripts are copied from DataLad (6307824f2), with slight
modifications.
> TST: travis: Set up SSH for localhost

- .travis.yml
- reproman/interface/run.py
- reproman/interface/tests/test_run.py
- reproman/support/jobs/job_templates/runscript/base.template.sh
- reproman/support/jobs/job_templates/runscript/includes/create-ref.template.sh
- reproman/support/jobs/job_templates/runscript/includes/datalad-add.template.sh
- reproman/support/jobs/job_templates/runscript/includes/post-run.template.sh
- reproman/support/jobs/job_templates/runscript/includes/pre-run.template.sh
- reproman/support/jobs/job_templates/submission/condor.template
- reproman/support/jobs/job_templates/submission/local.template
- reproman/support/jobs/job_templates/submission/pbs.template
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/submitters.py
- reproman/support/jobs/tests/test_orchestrators.py
Rework the orchestrators and submitters to support concurrent subjobs.
In terms of the `run` interface, this introduces a `--batch-spec` flag and a `--batch-parameter` flag for simple cases.  These control the number of subjobs.
An example invocation would be:
```
reproman run --follow -r ss --sub condor --orc datalad-pair-run --bp 'thing=thing-*' \
--input '{p[thing]}' sh -c 'cat {p[thing]} {p[thing]} >doubled-{p[thing]}'
```
Assuming `[thing-a, thing-b, ...]` are globbed, that's equivalent to a --batch-spec with
```
thing:
- thing-a
- thing-b
[...]
```
> run: Parallel subjobs

- reproman/interface/tests/test_run.py
- reproman/resource/tests/test_base.py
- reproman/support/jobs/tests/test_orchestrators.py
- reproman/tests/test_interface.py
- reproman/tests/test_skip.py
```
pytest v5.0.0 contains 65c2a8192 (Remove ExceptionInfo.__str__,
falling back to __repr__, 2019-06-06), which leads to calls like
`assert in str(exc)` failing with message like
AssertionError: assert 'whatever' in '<ExceptionInfo ValueError tblen=2>'
We need to use the .value attribute, as some of our calls already
do.  (Other options would be to use the `match` keyword of
pytest.raises() or to call exc.match()).
```
> TST: Adjust ExceptionInfo use for compatiblity with pytest v5.0.0

- reproman/support/jobs/job_templates/runscript/datalad-pair-run.template.sh
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
- tools/ci/install_datalad
This is the first topic split from gh-452:
> * adjusting more tests to use SSH resource rather than a local shell resource.  This is important because much of prepare_remote() goes through a different code path if we use the local shell.
The runs in gh-452 failed with a Git protocol error.  That should be fixed with datalad/datalad#3616.  ~I haven't yet merged that into datalad's master branch because its Travis tests are currently pretty busy.  For now I'm putting a temporary commit at the tip of this PR so that we pull in that fix from a throw-away branch~ (edit: it's now in DataLad's master).
<details>
<summary>range-diff with gh-452</summary>
```
1:  9f9e34663 <  -:  --------- ENH: run: Abort if dataset is dirty
2:  94924225b <  -:  --------- STY: orchestrators: Convert string command …
```
> run: Use new ssh setup in tests (v2)

- reproman/support/jobs/job_templates/runscript/datalad-pair-run.template.sh
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
- tools/ci/install_datalad
This is the second topic split from gh-452:
> * improving the dirty checks, particularly when there are subdatasets.
This relies on (and is on top of) gh-453.  Here's the [restricted comparison][0].
[0]: https://github.com/repronim/reproman/compare/kyleam:run-more-ssh...kyleam:run-more-dirt
<details>
<summary>range-diff with gh-452</summary>
```
1:  9f9e34663 !  1:  84981a784 ENH: run: Abort if dataset is dirty
@@ reproman/support/jobs/orchestrators.py: def __init__(self, resource, submission_
_datalad_check_container(self.ds, self.job_spec)
-@@ reproman/support/jobs/tests/test_orchestrators.py: def test_orc_datalad_pair(job_spec, dataset, shell):
- @pytest.mark.integration
- def test_orc_datalad_abort_if_dirty(job_spec, dataset, shell):
+@@ …
```
> run: Improve dirty checks

- reproman/conftest.py
As of pytest 4.5.0, decorating tests with `pytest.mark.integration`
results in this warning:
PytestUnknownMarkWarning: Unknown pytest.mark.integration - is
this a typo?  You can register custom marks to avoid this warning
- for details, see https://docs.pytest.org/en/latest/mark.html
Avoid it by registering 'integration' as a known marker.
> TST: pytest: Register custom 'integration' mark

- reproman/interface/jobs.py
- reproman/interface/run.py
- reproman/support/jobs/job_templates/runscript/base.template.sh
- reproman/support/jobs/job_templates/submission/condor.template
- reproman/support/jobs/job_templates/submission/local.template
- reproman/support/jobs/job_templates/submission/pbs.template
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
This series adjusts `run` so that the job spec is included as a file in the `.reproman/jobs/` metadata directory.  This is useful for tracking information about previous runs.  It also provides a base spec file that can be tweaked and passed to `run --job-spec`.  (Right now we don't provide any convenience tooling around reusing a spec, but tracking it allows us to more easily do so in the future.)
> run: Dump job spec in meta_directory

- reproman/distributions/tests/test_docker.py
- reproman/interface/tests/test_create.py
- reproman/interface/tests/test_delete.py
- reproman/interface/tests/test_install.py
- reproman/interface/tests/test_login.py
- reproman/interface/tests/test_ls.py
- reproman/resource/docker_container.py
- reproman/resource/tests/test_docker_container.py
- reproman/resource/tests/test_session.py
- setup.py
```
The docker module hasn't been released under the name "docker-py"
since 2016 [0] and has seen many releases under the name "docker" [1].
So we've effectively been pinning the release to version 1.10.6 even
though the current version is 4.1.0.
To update to latest version, it looks like we can get by with
substituting APIClient for Client.  Set the new floor to version
2.3.0, the release that introduced APIClient.
[0]: https://pypi.org/project/docker-py
[1]: https://pypi.org/project/docker
```
Closes #387.
---
Light local testing suggests this might work, but let's see what the test run says.  Also, before merging, we should make sure `dockerpty` is hooked up correctly (see gh-387).
> MNT: Unpin docker-py

- reproman/interface/run.py
- reproman/utils.py
As of Python 3.3, the ABCs in the collections module are available
from collections.abc.  They remain exposed in `collections` for
compatibility reasons but are slated for removal (originally in Python
3.8, now in 3.9).
> MNT: Update collections.Mapping for new location

- reproman/resource/docker_container.py
- reproman/resource/tests/test_docker_container.py
If a tag or digest isn't specified when calling `reproman create`, we
download all tagged images.  This behavior will likely be confusing to
any callers that are familiar with the command-line interface to
docker pull, which defaults to :latest if a tag or digest is omitted.
And the behavior doesn't fit our goal: starting a new container from a
single image.
Teach the DockerContainer resource to append ":latest" when it
receives a bare image name.
Closes #483.
> ENH: docker: Pull :latest if no tag or digest is specified

- docs/Makefile
- docs/source/acknowledgements.rst
- docs/source/cmdline.rst
- docs/source/conf.py
- docs/source/execute.rst
- docs/source/index.rst
- docs/source/manage.rst
- docs/source/usecases/index.rst
- formatters.py
This series extends the documentation.  Commits 1-4 are cleanup/setup commits.  Commit 5 adds a page on managing resources, and commit 6 adds a page on execution that's mostly dedicated to `reproman run`.  I'm not sure I'm happy with the state of the `run` parts, but I think it passes the threshold of "more useful than nothing at all".
To generate the html output for review, you can run `make -C docs html`.  Perhaps there's enough here that it's now worth hosting somewhere (probably either readthedocs or github pages).
> DOC: Add sections on managing resources and execution

- docs/Makefile
To resolve a hypothetical issue of no python3 executable being
available, while still allowing for virtualenv and system-wide
installation of sphinx.
I will merge if does not cause any breakage in CI
> RF: use python not python3 for running sphinx-build

- reproman/distributions/conda.py
distributions/conda.py has one place that triggers a SyntaxWarning during a fresh install.
> == for string comparison

- reproman/interface/jobs.py
- reproman/interface/tests/test_run.py
The first two commits are minor clean-ups around the same code path as the title issue, which is addressed by the final commit.
> jobs: Treat deleted local directory as orchestrator error

- .travis.yml
- CONTRIBUTING.md
- README.md
- setup.py
- tools/ci/install_datalad
Fix the [failing Travis build with master][0] by (1) bumping our required Python version to 3.5 and (2) using a released version of DataLad.
[0]: https://travis-ci.org/chaselgrove/reproman/builds/652585399
Closes #503
> travis: Fix failing master branch

- reproman/distributions/conda.py
- reproman/distributions/tests/test_conda.py
The download is failing due to a new redirect, causing `test_conda_init_install_and_detect` to fail.  Update the URL, and also tweak the `curl` call to avoid this issue in the future.
This isn't the full rework that our conda functionality needs (gh-446), but it's a prerequisite for that and should put master back into a passing state.
> Fix miniconda download

- reproman/distributions/conda.py
- reproman/distributions/piputils.py
- reproman/distributions/tests/test_conda.py
We've been pinning the miniconda URL since a6a571709 (2019-08-07) because our tests fails with the newer conda versions.  This series should bring the tests into a passing state with the latest conda.
```
[1/7] BF: conda: Add extension to temporary environment file
[2/7] RF: conda: Assume environments are in $root/envs
[3/7] RF: conda: Fill in editable packages
[4/7] OPT: conda: Avoid a call to pip
[5/7] TST: conda: Update some versions used in install test
[6/7] RF: conda: Avoid calling 'conda install' on root environment
[7/7] MNT: conda: Unpin conda URL
```
Fixes #446.
> Make conda tracer compatible with newer conda versions

- .travis.yml
- reproman/support/jobs/job_templates/submission/slurm.template
- reproman/support/jobs/submitters.py
- reproman/support/jobs/tests/test_orchestrators.py
- reproman/tests/skip.py
- tools/ci/setup-slurm-container.sh
This is an initial stab at Slurm support (gh-484).  There are still things to flesh out (most of the known ones should have to-do comment placeholders), and I bet someone familiar with Slurm could suggest better ways to do things (e.g., is it possible to get the job status as a JSON record?).  But I was able to submit simple commands (with a single job and with multiple subjobs), so things seem to be wired up correctly at least at a basic level.
---
Given that I don't have access to an environment with Slurm, setting that up was the more involved part.  Here are the details:
<details>
<summary>Slurm setup</summary>
* Clone <https://github.com/giovtorres/slurm-docker-cluster>
* Apply the patch at the end of this post.  It configures the image for ssh.  A few of the changes in that diff …
> run: Add Slurm support

- reproman/cmd.py
- reproman/support/external_versions.py
- reproman/tests/skip.py
The point is to check whether the functionality is available, so don't
pollute the test output with alarming things like
[ERROR  ] stderr| Error: communication error [..]
[ERROR  ] Failed to run ['condor_status'] under None. [...]
---
This is just a minor cosmetic thing that was bothering me as I was working on another topic.
> TST: skip: Quiet Runner-based dependency checks

- reproman/support/jobs/job_templates/runscript/base.template.sh
This series has a commit from @chaselgrove and one from @yarikoptic.  The first commit isn't strictly needed because the second drops the `find` call, but I think it is good to have that change in case we end up going back to a `find` call.
Based on looking at <https://ss64.com/osx/grep.html>, I think this grep call should be okay on macOS.
> runscript: Improve status file checks

- reproman/interface/jobs.py
Most likely it is just due to me having some elderly job records laying
around, which I will remove, but I do not think it is good to crash in
such cases
> ENH: skip with a warning a job which fails to render due to a missing key

- reproman/interface/run.py
If an invalid value for the submitter or orchestrator is given, run()
fails with an uninformative KeyError.  Add the accepted values as
constraints so that run() fails early with a helpful message.
This is an alternative to gh-517.
Suggested-by: @yarikoptic
> ENH: run: Specify constraints for --sub and --orc

- .travis.yml
- reproman/support/jobs/job_templates/runscript/datalad-pair-run.template.sh
- reproman/support/jobs/job_templates/runscript/datalad-pair.template.sh
- reproman/support/jobs/job_templates/runscript/includes/datalad-save.template.sh
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
- setup.py
- tools/ci/install_datalad
This series updates `run`-related functionality for changes in the next feature release of DataLad.  That version will contain some functionality that was prompted by issues on ReproMan's end, in particular improvements to `datalad update` and `datalad create-sibling`.
The changes above will require bumping our dependency to DataLad 0.13.0, so other commits in this series prune no longer needed compatibility kludges.  In addition, 0.13 removes the deprecated `datalad add` command, so a commit here migrates to `datalad save` (which was held off to retain compatibility with DataLad 0.11.x line).
I'm marking this as a draft because (1) this shouldn't be merged until DataLad 0.13.0 is released and (2) this should resolve at least a few open issues, but I still need to reference them in the …
> Updates for (unrelased) DataLad 0.13.0

- reproman/interface/run.py
Raise an InsufficientArgumentsError rather than a plain ValueError so
that cmdline.main calls print_usage() after catching it.  Showing this
output is consistent with what other commands do and saves callers
from needing to follow up with `reproman -h`.
Closes #466.
> ENH: run: Show usage help if command or resource isn't given

- reproman/support/jobs/orchestrators.py
As of cdce12249 (ENH: orchestrators(datalad-pair): Do a more targeted
update, 2020-04-09), we first try to merge in the job ref, and if that
fails, update() isn't called.  Set failure=True so that we do not try
to get output files with a working tree that has not been updated.
Reported-by: @yarikoptic
https://github.com/ReproNim/reproman/pull/527#discussion_r435427464
> BF: orchestrators: Don't try to get outputs if ref merge fails

- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
If the target directory on the remote doesn't exist, `DataladOrchestrator.prepare_remote()` checks whether a sibling of the same name exists and aborts if it does.  In gh-440, @yarikoptic points out that this is unnecessarily strict:
> I think that ideally it should not even complain/crash if remote is configured and has desired target path (I believe it is the fact here)
This series addresses that bit of gh-440.
> run: Don't abort if sibling unexpectedly exists but has expected target

- reproman/interface/ls.py
- reproman/interface/tests/test_ls.py
This allows a command-line caller to use `reproman ls` to check if a resource exists, as described at gh-521.
> ls: Give non-zero exit code when an unknown resource is specified

- reproman/resource/ssh.py
As explained in e381f4b69 (ENH: ssh: Log connection based on Fabric's
values, 2018-11-27), the Fabric switch means that ssh_config files are
now considered, and the host attribute can point to a nickname, with
things like port configured via ssh_config.
Advertise this to `reproman backend-parameters` callers.
> DOC: ssh: Mention that SSH config nickname is accepted as host

- docs/source/execute.rst
- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
This series, in particular the second commit, adds a new orchestrator to support the use case described in gh-460.
---
> run: Add orchestrator for local, in-place runs

- reproman/interface/create.py
This makes more sense to me, especially with the environment name being a naked command line argument (without a flag) -- which arguably belongs at the end of the command line -- but this isn't possible if -b slurps up everything following it.
> Require "-b" for each backend parameter given to "reproman create"

- reproman/resource/aws_ec2.py
Using repronim environment names for EC2 instances means that names that
make sense for repronim (e.g. "aws") can be unhelpful in the EC2 console.
Prepending 'reproman-' to the EC2 name is an indication that the instance
belongs to reproman.
> Prepend 'reproman-' to the AWS EC2 instance names

- reproman/support/jobs/orchestrators.py
- reproman/support/jobs/tests/test_orchestrators.py
Modify the plain orchestrator to fetch status, stdout, and stderr back for all jobs.
Closes #535
> Plain orchestrator basic fetch

- .travis.yml
- reproman/distributions/tests/test_venv.py
- setup.py
The first two commits prepare the `virtualenv: system_site_packages: true` job for an upgrade from Xenial to Bionic.  The last commit does the upgrade to get the CPython fix described at gh-542.
> Travis: Fix 'make -C doc ...' failure in --system-site-packages job

- reproman/interface/execute.py
--keep isn't available on CentOs 7. (It is on CentOs 8.)  Use zcat in
hopes of being more portable.
Closes #540.
> BF: execute: Avoid 'gunzip --keep' for portability

- reproman/support/jobs/job_templates/submission/lsf.template
- reproman/support/jobs/submitters.py
- reproman/support/jobs/tests/test_orchestrators.py
This PR adds an LSF submitter.
@kyleam, can you recommend the best way to test this?  I'd model off of condor and slurm, but I only see them in test_orchestrators.py (no references to CondorSubmitter or SlurmSubmitter in tests).
> LSF support

- reproman/support/jobs/orchestrators.py
DataladOrchestrator.prepare_remote() sets DATALAD_SSH_IDENTITYFILE so
that DataLad can work with SSH targets, in particular those for our
AwsEc2 resource, that need a custom key file that's not specified in
ssh_config.  Doing this in prepare_remote(), however, is problematic
because prepare_remote() isn't necessarily called before other methods
like fetch() that also require DATALAD_SSH_IDENTITYFILE to be
configured.  From the command line, this prevents fetching a job with
`reproman jobs` for a resource that depends on a custom key.
Move the DATALAD_SSH_IDENTITYFILE handling to __init__() so that it is
also in effect for resurrected orchestrators.
Fixes #561.
---
Given the current SSH setup for our tests, I haven't come up with a straightforward way to test this.
@chaselgrove If you have …
> BF: DataladOrchestrator: Set DATALAD_SSH_IDENTITYFILE in __init__

- .travis.yml
- reproman/__init__.py
- reproman/tests/test_api.py
- setup.py
This is a simpler version of https://github.com/ReproNim/reproman/pull/493/files
now that similar code is provided by etelemetry natively.
I decided not to issue warning in case of inability to check, but rather
just log at .debug level
> ENH: enable etelemetry

- reproman/resource/aws_condor.py
- reproman/resource/aws_ec2.py
- reproman/resource/tests/test_aws_ec2.py
- setup.py
Individual commits have more information.
Changes are quite sloppy but the goal was to make things work:
- the whole dance started with trying to establish a new `ec2_condor` and it asking me for which key_name I want as many times (in parallel) as the `size` ;)  now it would not ask at all!:
- asking for key_name and breeding keys is not nice/good -- now key matches the name by default and we "mint" key_filename to match
- now if we are to ask for a key_name, we would offer to choose from already present locally keys
- ec2_condor was not really usable without explicit specification of base dir to reside somewhere under `~/nfs-mount`.  Now should function "by default" since `~/.reproman` would be symlinked from that location
- unresolved stumbling point is …
> Various ENH + RF +BF to make aws_ec2 and ec2_condor (more) usable

- reproman/support/jobs/orchestrators.py
In DataLad v0.12.0 (c89746c27e), the "revision" key in the results for
`datalad subdatasets` was changed from "revision" to "gitshasum", and
the old name was kept around for compatibility.  The old key will be
removed in the upcoming 0.14 release (f5c3104d88).
Switch to using "gitshasum".  (Our minimum DataLad version is 0.13, so
a compatibility kludge isn't needed.)
Fixes #568.
> BF: orchestrators: Update for change in 'datalad subdatasets' key

- .github/workflows/test.yml
- reproman/distributions/tests/test_vcs.py
- reproman/support/jobs/tests/test_orchestrators.py
This series adjust for Git's 2.28's `init.defaultBranch` configuration option:
* Update a few test that fail when `init.defaultBranch` is set to a value other than "master".
* Set `init.defaultBranch` to a value other than "master" in the GitHub CI runs to (1) guard against regressions and (2) silence the many `init.defaultBranch` warnings emitted when running the tests.
~This PR is marked as a draft because it sits on top of gh-571.  Here's the effective diff: https://github.com/repronim/reproman/compare/migrate-to-github-ci...harcoded-master~
> Adjust tests for Git's init.defaultBranch

- reproman/cmdline/helpers.py
- reproman/distributions/debian.py
- reproman/dochelpers.py
- reproman/interface/base.py
- reproman/resource/tests/test_shell.py
- reproman/resource/tests/test_ssh.py
- reproman/support/constraints.py
- reproman/support/distributions/debian.py
- reproman/support/jobs/submitters.py
- reproman/support/param.py
- reproman/tests/test_cmdline_main.py
- reproman/tests/test_dochelpers.py
- reproman/tests/test_log.py
- reproman/tests/test_utils.py
- reproman/utils.py
- reproman/version.py
A good number of regexps and a few other strings don't use an r-prefix
when the string contains non-escape-sequence backslashes.  This
doesn't make a functional difference at the moment because, when
Python encounters a backslash that produces an invalid escape
sequence, it automatically escapes the backslash.  But Python 3.6 and
later give a DeprecationWarning (<https://bugs.python.org/issue32912>),
with the goal of eventually making invalid escape sequences a syntax
error.
---
~This PR is marked as a draft because it sits on top of gh-571.  Here's the effective diff: https://github.com/repronim/reproman/compare/migrate-to-github-ci...invalid-escapes~
> MNT: Avoid invalid escape sequences in strings

- docs/source/execute.rst
- reproman/support/jobs/orchestrators.py
'datalad publish' was marked as deprecated in 0.14 in favor of
'datalad push', which was added in 0.13 (ReproMan's current minimum
version).  For the purpose of prepare_remote(), the main differences
are 1) the '' value for --since must be spelled as '^', and 2) push()
must be called with data=auto to retain the behavior of the publish()
call (though going forward it's worth considering whether data=nothing
should be used instead).
> MNT: Use 'datalad push' instead of deprecated 'datalad publish'

- reproman/support/jobs/orchestrators.py
When 5f982f216 (2021-03-03) switched datalad-publish to datalad-push,
data="auto" was used to retain the behavior of the publish() call.
However, as mentioned in that commit and gh-575 [*], data="nothing" is
preferable here.  The original publish() call didn't use
transfer_data="auto" because there was an intent to transfer data
according to any configured preferred content; I just thoughtlessly
left the option at the default value.
[*] https://github.com/ReproNim/reproman/pull/575#issuecomment-790090050
> BF: orchestrators: Call datalad-push with --data=nothing

- reproman/support/jobs/job_templates/submission/launcher.template
- reproman/support/jobs/job_templates/submission/slurm.template
- reproman/support/jobs/tests/test_orchestrators.py
Submit templates direct subjob output to
`$metadir/{stdout,stderr}.{0,..,$subjobs - 1}`.  The recently added
launcher handling, however, breaks this setup, creating just two files
with all the output (one for stdout and one for stderr).  In the case
of Slurm, the output files are `$metadir/{stdout,stderr}.4294967294`
because the files are constructed with "%a", which gets set to the
above value when there is no job array [1].
Rework launcher.template so that stdout and stderr are written to the
expected files.
[1] https://slurm.schedmd.com/job_array.html
Re: #578
---
Thanks to @jdkent for reporting.
> BF: job_templates: Store launcher subjob output in expected files

- docs/source/glossary.rst
- readthedocs.yml
rtd now uses  v2  configuration, this PR updates to the new requirements.
To test I had rtd build from this branch. I've now reverted that setting change after build completed.
> Fix readthedocs build
